### ISSUE TITLE
Unread messages are not different than read messages

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#148]
There might be something wrong with the font or something. See the screenshot attached.
![unreademails](https://cloud.githubusercontent.com/assets/568111/5999325/0a8a9fb4-aad1-11e4-8ee3-b28b1555074e.png)
The first message on the screenshot should be marked as unread.

It occurs both in threaded and mode and un-threaded mode, in Chrome ~~and Firefox~~.

**Comment by clochix** [comment]
@jsilvestre could you check if message in list has the `unseen` class ? Font weight should be bold…

**Comment by jsilvestre** [comment]
I do have the `unseen` class, and the dev console tells me it should be bold.

**Comment by clochix** [comment]
The font we use in Cozy, Signika-light, has no "bold" style. Most browsers do some magic to simulate bold, but not Chrome on Mac OS. So unread messages are indistinguishable from read ones in Chrome.
For now, I will update the unread style, but we need to fix this font issue, because Signika-light is widely used on Cozy.

**Comment by frankrousseau** [comment]
Are you sure it isn't Signika?

**Comment by poupotte** [comment]
I can't test because I havn't Mac OS, @jsilvestre can you test this issue please ?

**Comment by jsilvestre** [comment]
Thank you very much, I can know see a difference \o/
