### ISSUE TITLE
Improve newline in mail edition

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#168]
In mail edition, a first newline should be a newline instead of a paragraph separation. 

In others words : 
   * A newline should display a little space between lines
   * Two newlines corresponds to a paragraph separation (bigger space)

**Comment by frankrousseau** [comment]
You can take Thunderbird as a reference.

**Comment by clochix** [comment]
http://www.w3.org/TR/2011/WD-html5-20110525/editing.html#contenteditable-br “UAs should offer a way for the user to request an explicit line break at the caret position without breaking the paragraph, e.g. as the default action of a keydown event whose identifier is the "Enter" key and that has a shift modifier set.”

**Comment by frankrousseau** [comment]
I think there is a misunderstanding. I'm not challenging the behavior of content editable widget, I'm just asking for a proper user experience for the email composition.

The user is used to email composers proposed by Gmail and Thunderbird. Because it's the norm form most people and, by the way, a pretty good one (the same used by desktop text editors), I think we should use it in the Cozy Mails application. 

If you are not ok with that, could your provide more explanation about your opinion? 

*NB: It doesn't matter if it's based on BR/P/DIV tags or stylesheets."

**Comment by clochix** [comment]
I checked in various email clients : 
 - Thunderbird seems to only use <BR>. Hitting Return two times inserts two BR, no new paragraph;
 - in Gmail, return seems to insert BR and a new paragraph. Paragraphs have no top nor bottom margin, so BR, DIV and P use the same space. There's no special behavior when hitting Return two times. So I think I will only remove margins from DIV and BR, to behave like Gmail.

**Comment by frankrousseau** [comment]
Ok

**Comment by poupotte** [comment]
Is it ok for you @frankrousseau with the new version ?

**Comment by frankrousseau** [comment]
On the composer side yes. But not on the receiver side. The mail received in Thunderbird, didn't match what I typed in Cozy Emails.

**Comment by poupotte** [comment]
Ok, thanks @frankrousseau . There is an other issue about this problem #200. That's why I validate this issue.
