### ISSUE TITLE
Problem with infinite scroll

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#188]
Remove a message/conversation breaks infinite scroll. 
It just displays : 'This is the end of the road'.

**Comment by clochix** [comment]
Sorry, I thought I commented on this one some days ago ☹
I haven't fixed it yet because I'm unable to reproduce it. I tried the step to reproduce you described to me, but it works on my machine, and looking at the code, I wasn't able to guess what could possibly go wrong. It's probably obvious, but I don't get it.

**Comment by clochix** [comment]
STR: only happened in conversation mode when deleting a conversation by selecting it in message list.

**Comment by poupotte** [comment]
It works well for me. Thanks @clochix .
