### ISSUE TITLE
Can't use emails with smtp server on alternate port

### ISSUE THREAD

**Issue by godfoder** [cozy/cozy-emails#206]
Trying out the version in NPM as of 10 minutes ago, I could not get emails to add an account with an smtp server running on port 587 (w/STARTTLS) it seemed to just overwrite the port number every time I tried to change it.

**Comment by clochix** [comment]
Thanks @godfoder for reporting, I can confirm the issue.

**Comment by clochix** [comment]
This bug is hard to reproduce. The account creation screen is randomly refreshed, probably due to some background update. It seems to only happen just after the server was started. Here's a patch that should fix this. It will be available in our next release, probably next week.
As a workaround, before this release, you may try to wait a few minutes after server start before trying to create the account. It's weird but it may work.

**Comment by poupotte** [comment]
@godfoder , you'll publish a new version today. Your issue should be solved.

**Comment by clochix** [comment]
@godfoder Have you found time to test if it now works for you ?
