### ISSUE TITLE
Make text easier to read by putting it at a higher position in the screen

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#242]
@clochix mentioned the fact that the text was displayed too far from the top. It made reading experience on small screen bad.

I fixed it in #227

**Comment by poupotte** [comment]
For me, text is now too close from the top (just my mind) : 
![padding](https://cloud.githubusercontent.com/assets/2659119/6871099/99e5c654-d4a0-11e4-97c8-baf25d0ead88.png)
Maybe, it should be better something between old and new version.

Moreover, infinite scroll seems broken, we have to click on 'More message' button. I'm not sure but it maybe due to this change. I open a new issue for this problem (#246).

**Comment by frankrousseau** [comment]
It's related to @m4dz changes.

**Comment by frankrousseau** [comment]
I modified only CSS, so the fact that infinite scroll is broken is due to something else.
