### ISSUE TITLE
In conversation reply doesn't immediately appears in the conversation

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#90]

**Comment by poupotte** [comment]
It works well. 

I have just one problem with draft. Indeed, if I begin to reply to an email, it creates a draft. I delete this draft. Draft is well marked as deleted but each time I open my message, I come back on my draft (because deleted messages are displayed). In my mind, it's a strange behavior.

I'm not sure for a perfect solution : 
* Don't display deleted messages
* Open conversation on the last non-deleted message
* Completely remove a draft (instead of put it in trash)

**Comment by clochix** [comment]
I think that when discading a draft, we should really remove it from the server instead of moving it to trash. @aenario are we able to do this server side ?
(also, for now, a deleted draft should'nt be opened in edit mode, I'll fix this)

**Comment by poupotte** [comment]
Thanks @clochix, I opened #309 to really remove draft.
